carts/urls.py
from django.urls import path
from .views import drop_carts, menu_cart_add, menu_cart_remove, menu_cart_update_pickup, checkout, checkout_success, get_times

urlpatterns = [
    path('add-menu-item/', menu_cart_add),
    path('remove-menu-item/', menu_cart_remove),
    path('update-pickup/', menu_cart_update_pickup),
    path('checkout/', checkout, name="checkout"),
    path('checkout-success/', checkout_success, name="success"),
    path('drop-carts/', drop_carts),
    path('get-times/', get_times)
]

catering/urls.py
from django.urls import path
from .views import home, quote, menu, detail

urlpatterns = [
    path('', home, name="home"),
    path('menu/', menu),
    path('request/', quote, name="request"),
    path('seasonal-menu/<slug>/', detail, name="menu-detail"),
]

dd/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

from accounts.views import login_view
from base.views import home, story, service_detail, contact
from gallery.views import GalleryHome

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('cart/', include(('carts.urls', 'carts'), namespace="carts")),
    path('contact/', contact, name="contact"),
    path('catering/', include(('catering.urls', 'catering'), namespace="catering")),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace="dashboard")),
    path('gallery/', GalleryHome, name="gallery"),
    path('login/', login_view, name="login"),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path('menus/', include(('menus.urls', 'menus'), namespace="menus")),
    path('story/', story, name="story"),
    path('services/<slug>/', service_detail, name="service-detail")
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse

from ckeditor.fields import RichTextField
from dd.utils import unique_slug_generator

class Service(models.Model):
    title               = models.CharField(max_length=270, unique=True)
    slug                = models.SlugField(blank=True, null=True)
    description         = RichTextField(blank=True, null=True)
    page_content        = RichTextField(blank=True, null=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('service-detail', args=[str(self.slug)])
    
    class Meta:
        ordering = ['title']

def service_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(service_pre_save_receiver, sender=Service)

class ContactRequest(models.Model):
    first_name          = models.CharField(max_length=270)
    last_name           = models.CharField(max_length=270)
    email               = models.EmailField()
    phone               = models.CharField(max_length=270, blank=True)
    message             = models.TextField()
    created             = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return 'Contact Request from %s %s' %(self.first_name, self.last_name)
    

base/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.core.mail import send_mail

from .models import Service, ContactRequest

import requests
import json
import sweetify

def contact(request):
    if request.method == 'POST':
        data = request.POST
        fname = data['first-name']
        lname = data['last-name']
        email = data['email']
        phone = data['phone']
        message = data['message']
        recaptcha = data['g-recaptcha-response']
        params = {'secret': str(settings.RECAPTCHA_SECRET_KEY), 'response': recaptcha}
        if recaptcha != '':
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=params)
            response = json.loads(r.content)
            if response['success'] == True:
                request_obj = ContactRequest()
                request_obj.first_name = fname
                request_obj.last_name = lname
                request_obj.email = email
                request_obj.phone = phone
                request_obj.message = message
                request_obj.save()
                request.session['alert_message'] = 'success'
                from_email = 'info@eliftcreations.com'
                notif_subject = "New Contact Us Request! | Dominique's Dishes"
                notif_content = render_to_string('contact-request-received.html', 
                {
                    'first_name': fname,
                    'last_name': lname,
                    'email': email,
                    'phone': phone,
                    'message': message,
                    'timestamp': request_obj.created
                })
                notif_plain_text = 'New Contact Request Received'
                send_mail(notif_subject, notif_plain_text, from_email, ['dominiquesdishes@gmail.com','carolyn@dominiquesdishes.com'], html_message=notif_content)
                sweetify.success(request, "Thanks! We've received your request", persistent='Ok')
            else:
                sweetify.error(request, 'Uh oh! Something went wrong. Please refresh and try again', persistent='Ok')
        else:
            sweetify.error(request, "Uh oh! We couldn't verify you're a human. Please refresh the page and try again", persistent='Ok')
        return redirect('/contact/')
    else:
        context = {
            'title': "Dominique's Dishes | Contact Us",
            'recaptcha_site_key': settings.RECAPTCHA_SITE_KEY
        }
        return render(request, 'contact.html', context)

def home(request):
    context = {
        'title': "Dominique's Dishes | Home"
    }
    return render(request, 'home.html', context)

def story(request):
    context = {
        'title': "Dominique's Dishes | Story"
    }
    return render(request, 'story.html', context)

def service_detail(request, slug):
    service_obj = Service.objects.get(slug=slug)
    context = {
        'title': "Dominique's Dishes | %s" %(service_obj.title),
        'service': service_obj,
    }
    return render(request, 'service-detail.html', context)

base/templates/base.html
{% load static %}
{% url 'carts:checkout' as checkout_url %}
{% url 'catering:home' as catering_url %}
{% url 'catering:request' as catering_request_url %}
{% url 'contact' as contact_url %}
{% url 'home' as home_url %}
{% url 'gallery' as gallery_url %}
{% url 'story' as story_url %}
{% url 'menus:home' as menus_url %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
        <title>{{ title }}</title>
        <meta name="description" content="{{ seo_description }}" />
        {% include 'css.html' %}
        {% include 'js.html' %}
        {% block extra_js %}{% endblock %}
    </head>
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="d-flex justify-content-between">
                <button class="hamburger hamburger--vortex sidenav-open d-lg-none" id="sidenav-toggle" type="button">
                    <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                    </span>
                </button>
                <div class="brand">
                    <a href="/">
                        <img src="{% static 'img/logo-h-newfont.png' %}" style="width: 100%;">
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav-links">
                        <li class="nav-item cl-effect-17 tracking-in-contract">
                            <a class="nav-link {% if request.path == home_url %}active{% endif %}" href="{{ home_url }}" data-hover="Home">Home</a>
                        </li>
                        <li class="nav-item cl-effect-17 tracking-in-contract2">
                            <a class="nav-link {% if request.path == story_url %}active{% endif %}" href="{{ story_url }}" data-hover="Story">Story</a>
                        </li>
                        <li class="nav-item cl-effect-17 tracking-in-contract3">
                            <a class="nav-link {% if request.path == gallery_url %}active{% endif %}" href="{{ gallery_url }}" data-hover="Gallery">Gallery</a>
                        </li>
                        <li class="nav-item cl-effect-17 tracking-in-contract4">
                            <a class="nav-link {% if request.path == menus_url %}active{% endif %}" href="{{ menus_url }}" data-hover="Menus">Menus</a>
                        </li>
                        <li class="nav-item cl-effect-17 tracking-in-contract4">
                            <a class="nav-link {% if request.path == catering_url %}active{% endif %}" href="{{ catering_url }}" data-hover="Catering">Catering</a>
                        </li>
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" role="button" id="dropdownMenuPillars" data-bs-toggle="dropdown" aria-expanded="false">More</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuPillars">
                                {% for service in services %}
                                <li><a class="dropdown-item" href="{{ service.get_absolute_url }}">{{ service.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item cl-effect-17 tracking-in-contract6">
                            <a class="nav-link" href="{{ contact_url }}" data-hover="Contact">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="nav-cart" id="{% if request.path != checkout_url %}show-cart{% else %}back-to-cart{% endif %}">
                    <i class="bi bi-bag"></i>
                    <div id="cart-counter">{{ cart_count }}</div>
                </div>
            </div>
        </nav>
        <div id="brush-container">
            <img src="{% static 'img/nav-shad.png' %}">
        </div>
        <div id="sidenav">
            <div id="sidenav-container">
                <div id="sidenav-header"></div>
                <div id="sidenav-body">
                    <ul>
                        <a href="{{ home_url }}"><li>Home</li></a>
                        <a href="{{ story_url }}"><li>Story</li></a>
                        <a href="{{ menus_url }}"><li>Order Online</li></a>
                        <a href="{{ catering_url }}"><li>Catering</li></a>
                        <a href="{{ menus_url }}"><li>Menus</li></a>
                        <a href="{{ gallery_url }}"><li>Gallery</li></a>
                        <a href="{{ contact_url }}"><li>Contact</li></a>
                    </ul>
                </div>
            </div>
        </div>
        <div id="sidenav-overlay"></div>
    </header>
    <body>
        
        <div id="content-body">
            {% block content %}
            {% endblock %}
            
        </div>
        <div class="hidden" id="cart-container">
            {{ cart }}
        </div>
        <div id="to-top">
            <i class="bi bi-arrow-up-circle"></i>
        </div>
        {% load sweetify %}
        {% sweetify %}
        
    </body>
    <footer class="text-center text-lg-start bg-dark text-muted">
       
        <section>
            <div class="text-center text-md-start">
                <div class="row">
                    <div class="col-md-12 col-lg-6 mx-auto" style="display: flex; justify-content: center">
                        <a href="{{ home_url }}">
                            <img src="{% static 'img/logo-h-ko.png' %}" class="logo" style="width: 200px;">
                        </a>
                    </div>
                    <div class="col-12 center-align">
                        <div class="div-mini-dotted white" style="margin-bottom: 20px;"></div>
                    </div>
                    <div class="col-md-3 col-lg-1 col-xl-1 offset-md-4 offset-lg-5">
                        <p>
                            <a href="{{ home_url }}" class="text-reset">Home</a>
                        </p>
                        <p>
                            <a href="{{ menus_url }}" class="text-reset">Order</a>
                        </p>
                        <p>
                            <a href="{{ story_url }}" class="text-reset">Story</a>
                        </p>
                        
                    </div>
                    <div class="col-md-2 col-lg-2" id="footer-col-2">
                        <p>
                            <a href="{{ gallery_url }}" class="text-reset">Gallery</a>
                        </p>
                    <p>
                        <a href="{{ menus_url }}" class="text-reset">Menus</a>
                    </p>
                    
                    <p>
                        <a href="{{ contact_url }}" class="text-reset">Contact</a>
                    </p>
                    </div>
                    <div class="col-12 center-align">
                        <div class="divider light" style="margin-bottom: 5px; margin-top: 0px;"></div>
                    </div>
                    <p class="center-align" style="margin-bottom: 0px;">
                        <a href="https://www.facebook.com/profile.php?id=100069985220005" target="_blank"><i class="bi bi-facebook facebook-btn"></i></a>
                        <a href="https://www.instagram.com/dominiquesdishes/" target="_blank"><i class="bi bi-instagram ig-btn"></i></a>
                        <a href="https://www.yelp.com/biz/dominiques-dishes-wharton?utm_campaign=www_business_share_popup&utm_medium=copy_link&utm_source=(direct)" target="_blank"><i class="bi bi-yelp yelp-btn"></i></a>
                    </p>
                    <div class="col-12 center-align">
                        <div class="divider light" style="margin-bottom: 0px; margin-top: 5px;"></div>
                    </div>
                </div>
            </div>
        </section>
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.223);">
        © {% now 'Y' %} Copyright
        <a class="text-reset fw-bold">Dominique's Dishes</a>
        </div>
    </footer>
</html>

base/templates/contact-request-received.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<!--[if gte mso 9]>
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
<![endif]-->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="x-apple-disable-message-reformatting">
  <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge"><!--<![endif]-->
  <title></title>
  
    <style type="text/css">
      @media only screen and (min-width: 620px) {
  .u-row {
    width: 600px !important;
  }
  .u-row .u-col {
    vertical-align: top;
  }

  .u-row .u-col-100 {
    width: 600px !important;
  }

}

@media (max-width: 620px) {
  .u-row-container {
    max-width: 100% !important;
    padding-left: 0px !important;
    padding-right: 0px !important;
  }
  .u-row .u-col {
    min-width: 320px !important;
    max-width: 100% !important;
    display: block !important;
  }
  .u-row {
    width: 100% !important;
  }
  .u-col {
    width: 100% !important;
  }
  .u-col > div {
    margin: 0 auto;
  }
}
body {
  margin: 0;
  padding: 0;
}

table,
tr,
td {
  vertical-align: top;
  border-collapse: collapse;
}

p {
  margin: 0;
}

.ie-container table,
.mso-container table {
  table-layout: fixed;
}

* {
  line-height: inherit;
}

a[x-apple-data-detectors='true'] {
  color: inherit !important;
  text-decoration: none !important;
}

table, td { color: #000000; } @media (max-width: 480px) { #u_content_heading_1 .v-container-padding-padding { padding: 40px 10px 0px !important; } #u_content_text_1 .v-container-padding-padding { padding: 5px 10px 20px !important; } #u_content_image_1 .v-container-padding-padding { padding: 10px 10px 36px !important; } #u_content_heading_2 .v-container-padding-padding { padding: 40px 10px 0px !important; } #u_content_heading_2 .v-font-size { font-size: 20px !important; } #u_content_heading_2 .v-text-align { text-align: left !important; } #u_content_text_3 .v-container-padding-padding { padding: 10px !important; } #u_content_text_3 .v-text-align { text-align: left !important; } #u_content_text_3 .v-line-height { line-height: 140% !important; } }
    </style>
  
  

<!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet" type="text/css"><!--<![endif]-->

</head>

<body class="clean-body u_body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000">
  <!--[if IE]><div class="ie-container"><![endif]-->
  <!--[if mso]><div class="mso-container"><![endif]-->
  <table style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%" cellpadding="0" cellspacing="0">
  <tbody>
  <tr style="vertical-align: top">
    <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top">
    <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td align="center" style="background-color: #ffffff;"><![endif]-->
    

<div class="u-row-container" style="padding: 0px;background-image: url('https://pub-fd2af11a7ae344f8bdbc89c751d1e5bb.r2.dev/dd-img-1.png');background-repeat: no-repeat;background-position: center top;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
    <div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
      <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding: 0px;background-image: url('images/image-1.png');background-repeat: no-repeat;background-position: center top;background-color: transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:600px;"><tr style="background-color: transparent;"><![endif]-->
      
<!--[if (mso)|(IE)]><td align="center" width="600" style="width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="height: 100%;width: 100% !important;">
  <!--[if (!mso)&(!IE)]><!--><div style="box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;"><!--<![endif]-->
  
<table id="u_content_heading_1" style="font-family:'Open Sans',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:60px 10px 0px;font-family:'Open Sans',sans-serif;" align="left">
        
  <h1 class="v-text-align v-line-height v-font-size" style="margin: 0px; color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word; font-size: 30px; "><strong>Contact Request Received</strong></h1>

      </td>
    </tr>
  </tbody>
</table>

<table id="u_content_text_1" style="font-family:'Open Sans',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:5px 60px 10px;font-family:'Open Sans',sans-serif;" align="left">
        
  <div class="v-text-align v-line-height v-font-size" style="color: #ced4d9; line-height: 140%; text-align: center; word-wrap: break-word;">
    <p style="line-height: 140%;">A new contact request has been received through DominiquesDishes.com. Don't forget to follow up!</p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table id="u_content_image_1" style="font-family:'Open Sans',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Open Sans',sans-serif;" align="left">
        
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td class="v-text-align" style="padding-right: 0px;padding-left: 0px;" align="center">
      
      <img align="center" border="0" src="https://pub-fd2af11a7ae344f8bdbc89c751d1e5bb.r2.dev/dd-img-2.png" alt="image" title="image" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 77%;max-width: 446.6px;" width="446.6"/>
      
    </td>
  </tr>
</table>

      </td>
    </tr>
  </tbody>
</table>

  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
  </div>
</div>
<!--[if (mso)|(IE)]></td><![endif]-->
      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
    </div>
  </div>
</div>



<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
    <div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
      <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding: 0px;background-color: transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:600px;"><tr style="background-color: transparent;"><![endif]-->
      
<!--[if (mso)|(IE)]><td align="center" width="600" style="width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;" valign="top"><![endif]-->
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">
  <!--[if (!mso)&(!IE)]><!--><div style="box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><!--<![endif]-->
  
<table id="u_content_heading_2" style="font-family:'Open Sans',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:20px 50px 0px;font-family:'Open Sans',sans-serif;" align="left">
        
  <h1 class="v-text-align v-line-height v-font-size" style="margin: 0px; line-height: 140%; text-align: center; word-wrap: break-word; font-size: 24px; "><strong>Request Details</strong></h1>

      </td>
    </tr>
  </tbody>
</table>

<table id="u_content_text_3" style="font-family:'Open Sans',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:10px 50px;font-family:'Open Sans',sans-serif;" align="left">
        
  <div class="v-text-align v-line-height v-font-size" style="line-height: 170%; text-align: justify; word-wrap: break-word;">
    <p style="line-height: 170%;"><b>Name:</b> {{ first_name }} {{ last_name }}</p>
<p style="line-height: 170%;"><b>Email:</b> {{ email }}</p>
<p style="line-height: 170%;"><b>Phone:</b> {{ phone }}</p>
<p style="line-height: 170%;"><b>Message:</b> {{ message }}</p>
<p style="line-height: 170%;"><b>Timestamp:</b> {{ timestamp }}</p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
  </div>
</div>
<!--[if (mso)|(IE)]></td><![endif]-->
      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
    </div>
  </div>
</div>



<div class="u-row-container" style="padding: 0px 0px 50px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
    <div style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
      <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding: 0px 0px 50px;background-color: transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width:600px;"><tr style="background-color: transparent;"><![endif]-->
      
<!--[if (mso)|(IE)]><td align="center" width="600" style="width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;" valign="top"><![endif]-->
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">
  <!--[if (!mso)&(!IE)]><!--><div style="box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;"><!--<![endif]-->
  
<table style="font-family:'Open Sans',sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td class="v-container-padding-padding" style="overflow-wrap:break-word;word-break:break-word;padding:0px 0px 10px;font-family:'Open Sans',sans-serif;" align="left">
        
  <table height="0px" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
    <tbody>
      <tr style="vertical-align: top">
        <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
          <span>&#160;</span>
        </td>
      </tr>
    </tbody>
  </table>

      </td>
    </tr>
  </tbody>
</table>

  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
  </div>
</div>
<!--[if (mso)|(IE)]></td><![endif]-->
      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
    </div>
  </div>
</div>


    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->
    </td>
  </tr>
  </tbody>
  </table>
  <!--[if mso]></div><![endif]-->
  <!--[if IE]></div><![endif]-->
</body>

</html>